version: '3.9'

secrets:
  telegram_token:
    file: /Users/ithersta/unistart/.token

services:
  db:
    image: "postgres:14"
    environment:
      POSTGRES_DB: unistart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: "dpage/pgadmin4:6.13"
    environment:
      PGADMIN_DEFAULT_EMAIL: schilyaev.vlad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: unistart_default_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15433:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build: .
    restart: always
    depends_on:
      - db
    secrets:
      - telegram_token
    environment:
      DATABASE_NAME: unistart
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SERVER: db
      DUMP_USER_ID: 105293829
      TOKEN_FILE: /run/secrets/telegram_token
    #volumes:
    #  - app:/

volumes:
  postgres:
  pgadmin:
  app:
